/**
 * Sample Brasaland entities for exercising later utilities.
 * Official CONTEXT fixtures are included; extras add category, status,
 * capacity, payment, date, and waste-reason variety.
 * Objects named `invalid*` deliberately break documented validation rules
 * (WasteRecord has no CONTEXT validation rules; invalidWasteRecord uses
 * zero quantity, zero cost, and empty reportedBy as stand-ins).
 */

import type {
  Location,
  MenuItem,
  SaleTransaction,
  WasteRecord,
} from "./models";

export const sampleMenuItems: MenuItem[] = [
  {
    id: "ITEM-PICANHA-250",
    name: "Picanha 250g",
    category: "Meat",
    basePrice: { USD: 18.5, COP: 74000 },
    ingredientCost: { USD: 7.2, COP: 28800 },
    prepTimeMinutes: 15,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-FRIES",
    name: "French Fries",
    category: "Side",
    basePrice: { USD: 4.5, COP: 18000 },
    ingredientCost: { USD: 1.2, COP: 4800 },
    prepTimeMinutes: 8,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-COKE",
    name: "Coca-Cola",
    category: "Beverage",
    basePrice: { USD: 2.5, COP: 10000 },
    ingredientCost: { USD: 0.8, COP: 3200 },
    prepTimeMinutes: 2,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-BRIGADEIRO",
    name: "Brigadeiro",
    category: "Dessert",
    basePrice: { USD: 3.5, COP: 14000 },
    ingredientCost: { USD: 0.9, COP: 3600 },
    prepTimeMinutes: 5,
    isAvailableInColombia: true,
    isAvailableInUSA: false,
    allergens: ["milk", "soy"],
    status: "Active",
  },
  {
    id: "ITEM-COMBO-PICANHA",
    name: "Picanha Combo",
    category: "Combo",
    basePrice: { USD: 24.0, COP: 96000 },
    ingredientCost: { USD: 9.5, COP: 38000 },
    prepTimeMinutes: 18,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-CHORIZO-SEASONAL",
    name: "Fire-Roasted Chorizo",
    category: "Meat",
    basePrice: { USD: 12.0, COP: 48000 },
    ingredientCost: { USD: 4.5, COP: 18000 },
    prepTimeMinutes: 12,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Seasonal",
  },
  {
    id: "ITEM-OLD-SALAD",
    name: "House Salad",
    category: "Side",
    basePrice: { USD: 5.0, COP: 20000 },
    ingredientCost: { USD: 1.5, COP: 6000 },
    prepTimeMinutes: 6,
    isAvailableInColombia: false,
    isAvailableInUSA: true,
    allergens: [],
    status: "Discontinued",
  },
];

/** Breaks: empty name, prepTimeMinutes 0, prices not > 0, available nowhere. */
export const invalidMenuItem: MenuItem = {
  id: "ITEM-INVALID",
  name: "",
  category: "Meat",
  basePrice: { USD: 0, COP: 0 },
  ingredientCost: { USD: -1, COP: -1 },
  prepTimeMinutes: 0,
  isAvailableInColombia: false,
  isAvailableInUSA: false,
  allergens: [],
  status: "Active",
};

export const sampleLocations: Location[] = [
  {
    id: "LOC-MEDELLIN-01",
    name: "Brasaland Medellín Centro",
    city: "Medellín",
    country: "Colombia",
    openingYear: 2008,
    seatingCapacity: 80,
    staffCount: 12,
    monthlyRentCost: { USD: 1500, COP: 6000000 },
    averageMonthlyUtilities: { USD: 400, COP: 1600000 },
    manager: "Carlos Jiménez",
    status: "Active",
  },
  {
    id: "LOC-MIAMI-01",
    name: "Brasaland Miami Beach",
    city: "Miami",
    country: "USA",
    openingYear: 2018,
    seatingCapacity: 100,
    staffCount: 15,
    monthlyRentCost: { USD: 5500, COP: 22000000 },
    averageMonthlyUtilities: { USD: 800, COP: 3200000 },
    manager: "Jake Morrison",
    status: "Active",
  },
  {
    id: "LOC-BOGOTA-01",
    name: "Brasaland Bogotá Chapinero",
    city: "Bogotá",
    country: "Colombia",
    openingYear: 2012,
    seatingCapacity: 60,
    staffCount: 10,
    monthlyRentCost: { USD: 1800, COP: 7200000 },
    averageMonthlyUtilities: { USD: 450, COP: 1800000 },
    manager: "Laura Restrepo",
    status: "Active",
  },
  {
    id: "LOC-ORLANDO-01",
    name: "Brasaland Orlando Downtown",
    city: "Orlando",
    country: "USA",
    openingYear: 2020,
    seatingCapacity: 120,
    staffCount: 18,
    monthlyRentCost: { USD: 4800, COP: 19200000 },
    averageMonthlyUtilities: { USD: 700, COP: 2800000 },
    manager: "Ana Castillo",
    status: "Temporarily closed",
  },
  {
    id: "LOC-CALI-01",
    name: "Brasaland Cali Granada",
    city: "Cali",
    country: "Colombia",
    openingYear: 2015,
    seatingCapacity: 70,
    staffCount: 11,
    monthlyRentCost: { USD: 1200, COP: 4800000 },
    averageMonthlyUtilities: { USD: 350, COP: 1400000 },
    manager: "Diego Vargas",
    status: "Under renovation",
  },
];

/** Breaks: openingYear < 2008, seatingCapacity 0, staffCount 0, costs not > 0. */
export const invalidLocation: Location = {
  id: "LOC-INVALID",
  name: "Brasaland Invalid",
  city: "Nowhere",
  country: "Colombia",
  openingYear: 2007,
  seatingCapacity: 0,
  staffCount: 0,
  monthlyRentCost: { USD: 0, COP: 0 },
  averageMonthlyUtilities: { USD: 0, COP: 0 },
  manager: "",
  status: "Active",
};

export const sampleSales: SaleTransaction[] = [
  {
    id: "TXN-2024-15482",
    locationId: "LOC-MEDELLIN-01",
    itemId: "ITEM-PICANHA-250",
    quantity: 2,
    totalPrice: { USD: 37.0, COP: 148000 },
    paymentMethod: "Credit card",
    timestamp: new Date("2024-03-15T19:30:00"),
    waiterName: "María González",
  },
  {
    id: "TXN-2024-15483",
    locationId: "LOC-MIAMI-01",
    itemId: "ITEM-FRIES",
    quantity: 3,
    totalPrice: { USD: 13.5, COP: 54000 },
    paymentMethod: "Cash",
    timestamp: new Date("2024-03-15T20:15:00"),
    waiterName: "John Smith",
  },
  {
    id: "TXN-2024-15484",
    locationId: "LOC-MEDELLIN-01",
    itemId: "ITEM-COKE",
    quantity: 4,
    totalPrice: { USD: 10.0, COP: 40000 },
    paymentMethod: "Debit card",
    timestamp: new Date("2024-03-16T12:00:00"),
    waiterName: "María González",
  },
  {
    id: "TXN-2024-15485",
    locationId: "LOC-BOGOTA-01",
    itemId: "ITEM-COMBO-PICANHA",
    quantity: 1,
    totalPrice: { USD: 24.0, COP: 96000 },
    paymentMethod: "Digital wallet",
    timestamp: new Date("2024-03-16T18:45:00"),
    waiterName: "Sofía Méndez",
  },
  {
    id: "TXN-2024-15486",
    locationId: "LOC-MIAMI-01",
    itemId: "ITEM-PICANHA-250",
    quantity: 1,
    totalPrice: { USD: 18.5, COP: 74000 },
    paymentMethod: "Credit card",
    timestamp: new Date("2024-03-17T21:00:00"),
    waiterName: "John Smith",
  },
  {
    id: "TXN-2024-15487",
    locationId: "LOC-BOGOTA-01",
    itemId: "ITEM-BRIGADEIRO",
    quantity: 5,
    totalPrice: { USD: 17.5, COP: 70000 },
    paymentMethod: "Cash",
    timestamp: new Date("2024-03-17T15:20:00"),
    waiterName: "Sofía Méndez",
  },
];

/** Breaks: quantity 0, prices not > 0, empty waiterName. */
export const invalidSaleTransaction: SaleTransaction = {
  id: "TXN-INVALID",
  locationId: "LOC-MEDELLIN-01",
  itemId: "ITEM-PICANHA-250",
  quantity: 0,
  totalPrice: { USD: 0, COP: 0 },
  paymentMethod: "Cash",
  timestamp: new Date("2024-03-15T12:00:00"),
  waiterName: "",
};

export const sampleWasteRecords: WasteRecord[] = [
  {
    id: "WST-2024-001",
    locationId: "LOC-MEDELLIN-01",
    itemId: "ITEM-PICANHA-250",
    quantity: 1,
    reason: "Expired",
    cost: { USD: 7.2, COP: 28800 },
    timestamp: new Date("2024-03-15T22:00:00"),
    reportedBy: "Carlos Jiménez",
  },
  {
    id: "WST-2024-002",
    locationId: "LOC-MIAMI-01",
    itemId: "ITEM-FRIES",
    quantity: 2,
    reason: "Cooking error",
    cost: { USD: 2.4, COP: 9600 },
    timestamp: new Date("2024-03-16T14:30:00"),
    reportedBy: "Jake Morrison",
  },
  {
    id: "WST-2024-003",
    locationId: "LOC-BOGOTA-01",
    itemId: "ITEM-BRIGADEIRO",
    quantity: 3,
    reason: "Customer return",
    cost: { USD: 2.7, COP: 10800 },
    timestamp: new Date("2024-03-16T19:00:00"),
    reportedBy: "Laura Restrepo",
  },
  {
    id: "WST-2024-004",
    locationId: "LOC-MEDELLIN-01",
    itemId: "ITEM-COKE",
    quantity: 1,
    reason: "Damage",
    cost: { USD: 0.8, COP: 3200 },
    timestamp: new Date("2024-03-17T10:15:00"),
    reportedBy: "María González",
  },
  {
    id: "WST-2024-005",
    locationId: "LOC-ORLANDO-01",
    itemId: "ITEM-COMBO-PICANHA",
    quantity: 1,
    reason: "Other",
    cost: { USD: 9.5, COP: 38000 },
    timestamp: new Date("2024-03-17T11:00:00"),
    reportedBy: "Ana Castillo",
  },
];

/**
 * CONTEXT defines no WasteRecord validation rules.
 * Marked invalid via zero quantity, zero cost, and empty reportedBy.
 */
export const invalidWasteRecord: WasteRecord = {
  id: "WST-INVALID",
  locationId: "LOC-MEDELLIN-01",
  itemId: "ITEM-PICANHA-250",
  quantity: 0,
  reason: "Other",
  cost: { USD: 0, COP: 0 },
  timestamp: new Date("2024-03-15T12:00:00"),
  reportedBy: "",
};
